# -*- coding: utf-8 -*-
"""Project-sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFMOK1l4AQWfp6CZ-ghc3cb6mG9VYQzs
"""

#installing Dependencies
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

"""Download dataset"""

path='/content/datas'
files = [file for file in os.listdir(path)]
for file in files:
  print(file)

"""Get a dataset"""

my_datas = pd.DataFrame()
for file in files:
    current_data = pd.read_csv(path + '/' + file)
    my_datas = pd.concat([my_datas, current_data], ignore_index=True)

my_datas.head(5)

my_datas.shape

my_datas.isnull().sum()

my_datas.dropna(how='all', inplace=True)
my_datas.shape

my_datas.isnull().sum()

my_datas.dtypes

my_datas.head(5)

def month(x):
  return x.split('/')[0]

my_datas['Month']=my_datas['Order Date'].apply(month)
my_datas.head(5)

my_datas['Month'].unique()

my_datas=my_datas[my_datas['Month']!= 'Order Date']

my_datas['Month'].unique()

my_datas['Month'] = my_datas['Month'].astype(int)

my_datas['Quantity Ordered'] = my_datas['Quantity Ordered'].astype(int)
my_datas['Price Each'] = my_datas['Price Each'].astype(float)

my_datas.dtypes

my_datas['Sales'] = my_datas['Quantity Ordered'] * my_datas['Price Each']
my_datas.head(5)

"""# What is the month during which we achieved the highest revenue?"""

my_datas.groupby('Month')['Sales'].sum()

my_datas.groupby('Month')['Sales'].sum().plot.bar()

"""# In which city did we record the highest number of orders?"""

my_datas.head(5)

def city(x):
  return x.split(',')[1]

my_datas['City'] = my_datas['Purchase Address'].apply(city)
my_datas.head(5)

my_datas.groupby('City')['Quantity Ordered'].sum()

my_datas.groupby('City')['Quantity Ordered'].sum().plot.bar()

"""# When is the best time to run an advertising campaign to increase sales?"""

my_datas.head(5)

my_datas['Hours'] = pd.to_datetime(my_datas['Order Date']).dt.hour
my_datas.head(5)

hours =[]
keys =[]
for key, hour in my_datas.groupby('Hours'):
  keys.append(key)
  hours.append(len(hour))

my_datas.groupby('Hours')['Quantity Ordered'].sum().plot()

"""# Which product sells the most?"""

my_datas.head(5)

my_datas.groupby('Product')['Quantity Ordered'].sum().plot.bar()

my_datas.head(5)

